In [38]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [39]:
df = pd.read_csv(r'F:\Pallavi\Learnings\Python\Modules\Deep_Learning\MLP\MLP_Regression\data\Exam_Score_Prediction.csv')
df

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19997,18,other,bba,6.50,71.3,yes,5.0,good,self-study,low,easy,86.5
19996,19998,18,male,b.com,3.71,41.6,no,5.9,average,coaching,medium,moderate,60.9
19997,19999,19,other,diploma,7.88,68.2,yes,4.6,poor,group study,low,easy,64.5
19998,20000,19,male,bba,4.60,76.3,no,6.1,good,self-study,medium,moderate,79.0
19999,20001,20,male,b.sc,7.50,47.9,yes,7.5,poor,coaching,medium,moderate,71.0

In [40]:
df.drop(columns = ['student_id'], inplace = True)
x = df.drop(columns = ['exam_score'])
y = df.exam_score
encoded = pd.get_dummies(x, dtype = int)
encoded

,age,study_hours,class_attendance,sleep_hours,gender_female,gender_male,gender_other,course_b.com,course_b.sc,course_b.tech,...,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,facility_rating_high,facility_rating_low,facility_rating_medium,exam_difficulty_easy,exam_difficulty_hard,exam_difficulty_moderate
0,17,2.78,92.9,7.4,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
1,23,3.37,64.8,4.6,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,1
2,22,7.88,76.8,8.5,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
3,20,0.67,48.4,5.8,0,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,1
4,20,0.89,71.6,9.8,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,18,6.50,71.3,5.0,0,0,1,0,0,0,...,0,0,0,1,0,1,0,1,0,0
19996,18,3.71,41.6,5.9,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
19997,19,7.88,68.2,4.6,0,0,1,0,0,0,...,1,0,0,0,0,1,0,1,0,0
19998,19,4.60,76.3,6.1,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,1
19999,20,7.50,47.9,7.5,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1

In [41]:
import pickle
feature_names = encoded.columns.tolist()
with open("feature_names.pkl", "wb") as f:
    pickle.dump(feature_names, f)

In [42]:
x_train,x_test,y_train,y_test = train_test_split(encoded, y,test_size=0.2, random_state=10)

In [43]:
model = Sequential()

model.add(Dense(units=8, activation='relu', input_dim=30))
model.add(Dense(units=4, activation='relu'))
model.add(Dense(units=1, activation='linear'))

model.compile(optimizer='adam', metrics=['r2_score'], loss='mean_squared_error')
history = model.fit(x_train, y_train, epochs=50, validation_split=0.2, batch_size=64,verbose=2)

F:\Pallavi\Learnings\Python\Modules\Deep_Learning\tensar\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
200/200 - 4s - 22ms/step - loss: 2363.6360 - r2_score: -5.5280e+00 - val_loss: 605.2519 - val_r2_score: -7.3758e-01
Epoch 2/50
200/200 - 1s - 7ms/step - loss: 382.3638 - r2_score: -5.6035e-02 - val_loss: 350.0852 - val_r2_score: -5.0372e-03
Epoch 3/50
200/200 - 1s - 5ms/step - loss: 328.9166 - r2_score: 0.0916 - val_loss: 325.9643 - val_r2_score: 0.0642
Epoch 4/50
200/200 - 1s - 6ms/step - loss: 305.9548 - r2_score: 0.1550 - val_loss: 301.1927 - val_r2_score: 0.1353
Epoch 5/50
200/200 - 1s - 6ms/step - loss: 282.0970 - r2_score: 0.2209 - val_loss: 275.7898 - val_r2_score: 0.2083
Epoch 6/50
200/200 - 1s - 6ms/step - loss: 257.6929 - r2_score: 0.2883 - val_loss: 249.9350 - val_r2_score: 0.2825
Epoch 7/50
200/200 - 1s - 6ms/step - loss: 232.5235 - r2_score: 0.3578 - val_loss: 222.7120 - val_r2_score: 0.3606
Epoch 8/50
200/200 - 1s - 6ms/step - loss: 206.5430 - r2_score: 0.4296 - val_loss: 195.0582 - val_r2_score: 0.4400
Epoch 9/50
200/200 - 2s - 12ms/step - loss: 180.4086 - r2_score: 0.5017 - val_loss: 167.8154 - val_r2_score: 0.5182
Epoch 10/50
200/200 - 1s - 6ms/step - loss: 155.1952 - r2_score: 0.5714 - val_loss: 142.6804 - val_r2_score: 0.5904
Epoch 11/50
200/200 - 1s - 7ms/step - loss: 133.1149 - r2_score: 0.6324 - val_loss: 122.2361 - val_r2_score: 0.6491
Epoch 12/50
200/200 - 1s - 6ms/step - loss: 116.3724 - r2_score: 0.6786 - val_loss: 108.1792 - val_r2_score: 0.6894
Epoch 13/50
200/200 - 1s - 6ms/step - loss: 105.1092 - r2_score: 0.7097 - val_loss: 99.9532 - val_r2_score: 0.7131
Epoch 14/50
200/200 - 1s - 6ms/step - loss: 98.8374 - r2_score: 0.7270 - val_loss: 96.2889 - val_r2_score: 0.7236
Epoch 15/50
200/200 - 1s - 6ms/step - loss: 96.4024 - r2_score: 0.7338 - val_loss: 94.6201 - val_r2_score: 0.7284
Epoch 16/50
200/200 - 1s - 6ms/step - loss: 95.4768 - r2_score: 0.7363 - val_loss: 94.3106 - val_r2_score: 0.7292
Epoch 17/50
200/200 - 1s - 6ms/step - loss: 95.2485 - r2_score: 0.7369 - val_loss: 94.8842 - val_r2_score: 0.7276
Epoch 18/50
200/200 - 1s - 6ms/step - loss: 95.3506 - r2_score: 0.7367 - val_loss: 97.0111 - val_r2_score: 0.7215
Epoch 19/50
200/200 - 1s - 6ms/step - loss: 95.3396 - r2_score: 0.7367 - val_loss: 94.2370 - val_r2_score: 0.7295
Epoch 20/50
200/200 - 2s - 8ms/step - loss: 95.2666 - r2_score: 0.7369 - val_loss: 94.2655 - val_r2_score: 0.7294
Epoch 21/50
200/200 - 1s - 6ms/step - loss: 95.2797 - r2_score: 0.7369 - val_loss: 94.7689 - val_r2_score: 0.7279
Epoch 22/50
200/200 - 1s - 6ms/step - loss: 95.3039 - r2_score: 0.7368 - val_loss: 94.8908 - val_r2_score: 0.7276
Epoch 23/50
200/200 - 1s - 6ms/step - loss: 95.3301 - r2_score: 0.7367 - val_loss: 94.9022 - val_r2_score: 0.7276
Epoch 24/50
200/200 - 1s - 5ms/step - loss: 95.2560 - r2_score: 0.7369 - val_loss: 94.9557 - val_r2_score: 0.7274
Epoch 25/50
200/200 - 1s - 5ms/step - loss: 95.4270 - r2_score: 0.7364 - val_loss: 94.4456 - val_r2_score: 0.7289
Epoch 26/50
200/200 - 1s - 6ms/step - loss: 95.1394 - r2_score: 0.7372 - val_loss: 94.3722 - val_r2_score: 0.7291
Epoch 27/50
200/200 - 1s - 6ms/step - loss: 95.2956 - r2_score: 0.7368 - val_loss: 95.2494 - val_r2_score: 0.7266
Epoch 28/50
200/200 - 1s - 7ms/step - loss: 95.1847 - r2_score: 0.7371 - val_loss: 94.3951 - val_r2_score: 0.7290
Epoch 29/50
200/200 - 1s - 6ms/step - loss: 95.4460 - r2_score: 0.7364 - val_loss: 94.3767 - val_r2_score: 0.7291
Epoch 30/50
200/200 - 1s - 6ms/step - loss: 95.5824 - r2_score: 0.7360 - val_loss: 94.3455 - val_r2_score: 0.7291
Epoch 31/50
200/200 - 1s - 7ms/step - loss: 95.1470 - r2_score: 0.7372 - val_loss: 94.4936 - val_r2_score: 0.7287
Epoch 32/50
200/200 - 1s - 6ms/step - loss: 95.1610 - r2_score: 0.7372 - val_loss: 95.3231 - val_r2_score: 0.7263
Epoch 33/50
200/200 - 1s - 6ms/step - loss: 95.2274 - r2_score: 0.7370 - val_loss: 94.3554 - val_r2_score: 0.7291
Epoch 34/50
200/200 - 1s - 6ms/step - loss: 95.1135 - r2_score: 0.7373 - val_loss: 94.5970 - val_r2_score: 0.7284
Epoch 35/50
200/200 - 1s - 6ms/step - loss: 95.2120 - r2_score: 0.7370 - val_loss: 94.3982 - val_r2_score: 0.7290
Epoch 36/50
200/200 - 1s - 5ms/step - loss: 95.2670 - r2_score: 0.7369 - val_loss: 94.3979 - val_r2_score: 0.7290
Epoch 37/50
200/200 - 1s - 5ms/step - loss: 95.2280 - r2_score: 0.7370 - val_loss: 94.4161 - val_r2_score: 0.7289
Epoch 38/50
200/200 - 1s - 6ms/step - loss: 95.1444 - r2_score: 0.7372 - val_loss: 94.4634 - val_r2_score: 0.7288
Epoch 39/50
200/200 - 1s - 6ms/step - loss: 95.3033 - r2_score: 0.7368 - val_loss: 94.5786 - val_r2_score: 0.7285
Epoch 40/50
200/200 - 2s - 8ms/step - loss: 95.1097 - r2_score: 0.7373 - val_loss: 94.4812 - val_r2_score: 0.7288
Epoch 41/50
200/200 - 1s - 7ms/step - loss: 95.1874 - r2_score: 0.7371 - val_loss: 94.5271 - val_r2_score: 0.7286
Epoch 42/50
200/200 - 1s - 6ms/step - loss: 95.2547 - r2_score: 0.7369 - val_loss: 94.8672 - val_r2_score: 0.7277
Epoch 43/50
200/200 - 1s - 6ms/step - loss: 95.1349 - r2_score: 0.7373 - val_loss: 94.3811 - val_r2_score: 0.7290
Epoch 44/50
200/200 - 1s - 6ms/step - loss: 95.2149 - r2_score: 0.7370 - val_loss: 94.5764 - val_r2_score: 0.7285
Epoch 45/50
200/200 - 1s - 6ms/step - loss: 95.3190 - r2_score: 0.7367 - val_loss: 95.0415 - val_r2_score: 0.7272
Epoch 46/50
200/200 - 1s - 6ms/step - loss: 95.0716 - r2_score: 0.7374 - val_loss: 94.3528 - val_r2_score: 0.7291
Epoch 47/50
200/200 - 2s - 11ms/step - loss: 95.2069 - r2_score: 0.7371 - val_loss: 94.3666 - val_r2_score: 0.7291
Epoch 48/50
200/200 - 1s - 6ms/step - loss: 95.2617 - r2_score: 0.7369 - val_loss: 94.8625 - val_r2_score: 0.7277
Epoch 49/50
200/200 - 1s - 6ms/step - loss: 95.1278 - r2_score: 0.7373 - val_loss: 94.9988 - val_r2_score: 0.7273
Epoch 50/50
200/200 - 1s - 6ms/step - loss: 95.4527 - r2_score: 0.7364 - val_loss: 94.3311 - val_r2_score: 0.7292

In [44]:
y_train_pred = model.predict(x_train)

mse = mean_squared_error(y_train, y_train_pred)
print("MSE : ",mse)
mae = mean_absolute_error(y_train, y_train_pred)
print("MAE : ", mae)
accuracy = r2_score(y_train, y_train_pred)
print("R2_Score", accuracy)

500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step
MSE :  94.7418048304199
MAE :  7.819248588565826
R2_Score 0.7363368127002836

In [45]:
y_test_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_test_pred)
print("MSE : ",mse)
mae = mean_absolute_error(y_test, y_test_pred)
print("MAE : ", mae)
accuracy = r2_score(y_test, y_test_pred)
print("R2_Score", accuracy)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
MSE :  100.11565288854287
MAE :  8.010465121765137
R2_Score 0.7139860430105747

In [46]:
model.save('AnnExamScoreModel.keras')

In [47]:
model.save('AnnExamScoreModel.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
# Training Accuracy = 0.7363368127002836
# Testing Accuracy = 0.7139860430105747

In [52]:
#Hyperparameter

In [53]:
import keras_tuner as kt

In [54]:
def build_Model(hp):
    model = Sequential()

    #Hiddlen layer 1
    unit_1 = hp.Int("unit_1", min_value= 8,max_value= 32, step =8)
    activ_fun1 = hp.Choice("activ_fun1", ["tanh","relu"])
    kernal_init1 = hp.Choice("kernal_init1",["he_normal","glorot_uniform"])
    model.add(Dense(units = unit_1, activation = activ_fun1, kernel_initializer=kernal_init1, input_dim=30))

    
     #Hiddlen layer 2
    unit_2 = hp.Int("unit_2", min_value= 4,max_value= 16, step =4)
    activ_fun2 = hp.Choice("activ_fun2", ["tanh","relu"])
    kernal_init2 = hp.Choice("kernal_init2",["he_normal","glorot_uniform"])
    model.add(Dense(units = unit_2, activation = activ_fun2, kernel_initializer=kernal_init2))

    #Output Layer
    model.add(Dense(units=1, activation="linear"))

    model.compile(optimizer="adam", metrics=["r2_score"],loss="mean_squared_error")

    return model

k_tuner = kt.RandomSearch(build_Model, max_trials= 4, objective="val_loss", project_name = "Proj1" )    
k_tuner.search(x_train,y_train, epochs=30, validation_data = (x_test,y_test), batch_size=256,verbose=2)

Trial 4 Complete [00h 01m 31s]
val_loss: 100.17628479003906

Best val_loss So Far: 99.99711608886719
Total elapsed time: 00h 05m 52s

In [55]:
k_tuner.get_best_hyperparameters(1)[0].values

{'unit_1': 16,
 'activ_fun1': 'relu',
 'kernal_init1': 'glorot_uniform',
 'unit_2': 16,
 'activ_fun2': 'relu',
 'kernal_init2': 'he_normal'}

In [ ]:
# Add best hyperprarameter and train model again to check acuracy

In [56]:
model = Sequential()

model.add(Dense(units=16, activation='relu', input_dim=30,kernel_initializer="glorot_uniform"))
model.add(Dense(units=16, activation='relu',kernel_initializer="he_normal"))
model.add(Dense(units=1, activation='linear'))

model.compile(optimizer='adam', metrics=['r2_score'], loss='mean_squared_error')
history = model.fit(x_train, y_train, epochs=50, validation_split=0.2, batch_size=128,verbose=2)

F:\Pallavi\Learnings\Python\Modules\Deep_Learning\tensar\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
100/100 - 4s - 44ms/step - loss: 5883.2617 - r2_score: -1.5249e+01 - val_loss: 3238.2983 - val_r2_score: -8.2966e+00
Epoch 2/50
100/100 - 1s - 9ms/step - loss: 1276.8833 - r2_score: -2.5265e+00 - val_loss: 308.0902 - val_r2_score: 0.1155
Epoch 3/50
100/100 - 1s - 7ms/step - loss: 298.4791 - r2_score: 0.1756 - val_loss: 297.5139 - val_r2_score: 0.1459
Epoch 4/50
100/100 - 1s - 7ms/step - loss: 287.6475 - r2_score: 0.2056 - val_loss: 278.9805 - val_r2_score: 0.1991
Epoch 5/50
100/100 - 1s - 15ms/step - loss: 263.7206 - r2_score: 0.2716 - val_loss: 247.8151 - val_r2_score: 0.2886
Epoch 6/50
100/100 - 1s - 10ms/step - loss: 231.3925 - r2_score: 0.3609 - val_loss: 208.0717 - val_r2_score: 0.4027
Epoch 7/50
100/100 - 1s - 8ms/step - loss: 188.4005 - r2_score: 0.4797 - val_loss: 161.8676 - val_r2_score: 0.5353
Epoch 8/50
100/100 - 1s - 8ms/step - loss: 145.3393 - r2_score: 0.5986 - val_loss: 124.1904 - val_r2_score: 0.6435
Epoch 9/50
100/100 - 1s - 13ms/step - loss: 114.8110 - r2_score: 0.6829 - val_loss: 102.9571 - val_r2_score: 0.7044
Epoch 10/50
100/100 - 1s - 7ms/step - loss: 101.5362 - r2_score: 0.7196 - val_loss: 97.0236 - val_r2_score: 0.7215
Epoch 11/50
100/100 - 1s - 10ms/step - loss: 97.5364 - r2_score: 0.7306 - val_loss: 95.4453 - val_r2_score: 0.7260
Epoch 12/50
100/100 - 1s - 7ms/step - loss: 96.6824 - r2_score: 0.7330 - val_loss: 95.8623 - val_r2_score: 0.7248
Epoch 13/50
100/100 - 1s - 14ms/step - loss: 96.1376 - r2_score: 0.7345 - val_loss: 94.9801 - val_r2_score: 0.7273
Epoch 14/50
100/100 - 1s - 8ms/step - loss: 95.7860 - r2_score: 0.7355 - val_loss: 94.9117 - val_r2_score: 0.7275
Epoch 15/50
100/100 - 1s - 13ms/step - loss: 95.2555 - r2_score: 0.7369 - val_loss: 97.0779 - val_r2_score: 0.7213
Epoch 16/50
100/100 - 1s - 13ms/step - loss: 96.0301 - r2_score: 0.7348 - val_loss: 94.8838 - val_r2_score: 0.7276
Epoch 17/50
100/100 - 2s - 15ms/step - loss: 95.3664 - r2_score: 0.7366 - val_loss: 95.4164 - val_r2_score: 0.7261
Epoch 18/50
100/100 - 1s - 8ms/step - loss: 95.4441 - r2_score: 0.7364 - val_loss: 94.9579 - val_r2_score: 0.7274
Epoch 19/50
100/100 - 1s - 7ms/step - loss: 95.2392 - r2_score: 0.7370 - val_loss: 95.0007 - val_r2_score: 0.7273
Epoch 20/50
100/100 - 1s - 13ms/step - loss: 95.4701 - r2_score: 0.7363 - val_loss: 95.1917 - val_r2_score: 0.7267
Epoch 21/50
100/100 - 1s - 15ms/step - loss: 95.1845 - r2_score: 0.7371 - val_loss: 94.9501 - val_r2_score: 0.7274
Epoch 22/50
100/100 - 1s - 8ms/step - loss: 95.3308 - r2_score: 0.7367 - val_loss: 95.0334 - val_r2_score: 0.7272
Epoch 23/50
100/100 - 1s - 13ms/step - loss: 95.3114 - r2_score: 0.7368 - val_loss: 94.8471 - val_r2_score: 0.7277
Epoch 24/50
100/100 - 1s - 14ms/step - loss: 95.1719 - r2_score: 0.7371 - val_loss: 95.1923 - val_r2_score: 0.7267
Epoch 25/50
100/100 - 1s - 9ms/step - loss: 95.3567 - r2_score: 0.7366 - val_loss: 95.5145 - val_r2_score: 0.7258
Epoch 26/50
100/100 - 1s - 8ms/step - loss: 95.3986 - r2_score: 0.7365 - val_loss: 94.9088 - val_r2_score: 0.7275
Epoch 27/50
100/100 - 1s - 8ms/step - loss: 95.4489 - r2_score: 0.7364 - val_loss: 95.3436 - val_r2_score: 0.7263
Epoch 28/50
100/100 - 1s - 14ms/step - loss: 95.3165 - r2_score: 0.7368 - val_loss: 97.8753 - val_r2_score: 0.7190
Epoch 29/50
100/100 - 1s - 7ms/step - loss: 96.3991 - r2_score: 0.7338 - val_loss: 95.2054 - val_r2_score: 0.7267
Epoch 30/50
100/100 - 1s - 14ms/step - loss: 95.3412 - r2_score: 0.7367 - val_loss: 94.9959 - val_r2_score: 0.7273
Epoch 31/50
100/100 - 1s - 15ms/step - loss: 95.2452 - r2_score: 0.7369 - val_loss: 95.1283 - val_r2_score: 0.7269
Epoch 32/50
100/100 - 1s - 7ms/step - loss: 95.1162 - r2_score: 0.7373 - val_loss: 95.7269 - val_r2_score: 0.7252
Epoch 33/50
100/100 - 1s - 8ms/step - loss: 95.0174 - r2_score: 0.7376 - val_loss: 94.7765 - val_r2_score: 0.7279
Epoch 34/50
100/100 - 1s - 8ms/step - loss: 95.1843 - r2_score: 0.7371 - val_loss: 94.8298 - val_r2_score: 0.7278
Epoch 35/50
100/100 - 1s - 8ms/step - loss: 96.0346 - r2_score: 0.7348 - val_loss: 94.8727 - val_r2_score: 0.7276
Epoch 36/50
100/100 - 1s - 7ms/step - loss: 95.1363 - r2_score: 0.7372 - val_loss: 94.7526 - val_r2_score: 0.7280
Epoch 37/50
100/100 - 1s - 7ms/step - loss: 95.2982 - r2_score: 0.7368 - val_loss: 97.1512 - val_r2_score: 0.7211
Epoch 38/50
100/100 - 1s - 14ms/step - loss: 95.2935 - r2_score: 0.7368 - val_loss: 96.2090 - val_r2_score: 0.7238
Epoch 39/50
100/100 - 1s - 8ms/step - loss: 95.1548 - r2_score: 0.7372 - val_loss: 94.8477 - val_r2_score: 0.7277
Epoch 40/50
100/100 - 1s - 7ms/step - loss: 95.4488 - r2_score: 0.7364 - val_loss: 95.2815 - val_r2_score: 0.7265
Epoch 41/50
100/100 - 1s - 8ms/step - loss: 95.2375 - r2_score: 0.7370 - val_loss: 94.7087 - val_r2_score: 0.7281
Epoch 42/50
100/100 - 1s - 13ms/step - loss: 95.2700 - r2_score: 0.7369 - val_loss: 94.6878 - val_r2_score: 0.7282
Epoch 43/50
100/100 - 1s - 8ms/step - loss: 95.0526 - r2_score: 0.7375 - val_loss: 95.0224 - val_r2_score: 0.7272
Epoch 44/50
100/100 - 1s - 7ms/step - loss: 95.5968 - r2_score: 0.7360 - val_loss: 95.0851 - val_r2_score: 0.7270
Epoch 45/50
100/100 - 1s - 7ms/step - loss: 95.2891 - r2_score: 0.7368 - val_loss: 94.9789 - val_r2_score: 0.7273
Epoch 46/50
100/100 - 1s - 8ms/step - loss: 95.2281 - r2_score: 0.7370 - val_loss: 94.7711 - val_r2_score: 0.7279
Epoch 47/50
100/100 - 1s - 14ms/step - loss: 95.2928 - r2_score: 0.7368 - val_loss: 95.5218 - val_r2_score: 0.7258
Epoch 48/50
100/100 - 1s - 8ms/step - loss: 95.3858 - r2_score: 0.7366 - val_loss: 94.8092 - val_r2_score: 0.7278
Epoch 49/50
100/100 - 1s - 13ms/step - loss: 95.3892 - r2_score: 0.7366 - val_loss: 94.6429 - val_r2_score: 0.7283
Epoch 50/50
100/100 - 1s - 6ms/step - loss: 94.9574 - r2_score: 0.7377 - val_loss: 94.6896 - val_r2_score: 0.7282

In [57]:
y_train_pred = model.predict(x_train)

mse = mean_squared_error(y_train, y_train_pred)
print("MSE : ",mse)
mae = mean_absolute_error(y_train, y_train_pred)
print("MAE : ", mae)
accuracy = r2_score(y_train, y_train_pred)
print("R2_Score", accuracy)


y_test_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_test_pred)
print("MSE : ",mse)
mae = mean_absolute_error(y_test, y_test_pred)
print("MAE : ", mae)
accuracy = r2_score(y_test, y_test_pred)
print("R2_Score", accuracy)

500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step
MSE :  94.72320536130789
MAE :  7.821487149539948
R2_Score 0.7363885743837023
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
MSE :  100.51417731667505
MAE :  8.032271579105378
R2_Score 0.7128475242539329

In [ ]:
# Training Accuracy = 0.7363885743837023
# Testing Accuracy = 0.7128475242539329

In [ ]:
# Add Optimizer

In [64]:
import keras

def build_Model(hp):
    model = Sequential()

    #Hiddlen layer 1
    unit_1 = hp.Int("unit_1", min_value= 8,max_value= 32, step =8)
    activ_fun1 = hp.Choice("activ_fun1", ["tanh","relu"])
    kernal_init1 = hp.Choice("kernal_init1",["he_normal","glorot_uniform"])
    model.add(Dense(units = unit_1, activation = activ_fun1, kernel_initializer=kernal_init1, input_dim=30))

    
     #Hiddlen layer 2
    unit_2 = hp.Int("unit_2", min_value= 4,max_value= 16, step =4)
    activ_fun2 = hp.Choice("activ_fun2", ["tanh","relu"])
    kernal_init2 = hp.Choice("kernal_init2",["he_normal","glorot_uniform"])
    model.add(Dense(units = unit_2, activation = activ_fun2, kernel_initializer=kernal_init2))

    #Output Layer
    model.add(Dense(units=1, activation="linear"))

    #Optimizer
    opt_choice = hp.Choice("opt_choice",["adam","sgd","rmsprop"])
    learning_rate = hp.Float("learning_rate", min_value = 0.001, max_value=0.1, step = 0.005)

    if opt_choice=="adam":
        optimizer = keras.optimizers.Adam(learning_rate = learning_rate)
    elif opt_choice=="sgd":
        optimizer = keras.optimizers.SGD(learning_rate = learning_rate)
    elif opt_choice=="rmsprop":
        optimizer = keras.optimizers.RMSprop(learning_rate = learning_rate)

    model.compile(optimizer=optimizer, metrics=["r2_score"],loss="mean_squared_error")

    return model

k_tuner = kt.RandomSearch(build_Model, max_trials= 4, objective="val_loss", project_name = "Proj1" )    
k_tuner.search(x_train,y_train, epochs=30, validation_data = (x_test,y_test), batch_size=256,verbose=2)

Trial 4 Complete [00h 00m 25s]
val_loss: 350.05096435546875

Best val_loss So Far: 350.0386657714844
Total elapsed time: 00h 01m 39s

### Batch Normalization

In [68]:
from tensorflow.keras.layers import BatchNormalization

In [70]:
import keras

def build_Model(hp):
    model = Sequential()

    #Hiddlen layer 1
    unit_1 = hp.Int("unit_1", min_value= 8,max_value= 32, step =8)
    activ_fun1 = hp.Choice("activ_fun1", ["tanh","relu"])
    kernal_init1 = hp.Choice("kernal_init1",["he_normal","glorot_uniform"])
    model.add(Dense(units = unit_1, activation = activ_fun1, kernel_initializer=kernal_init1, input_dim=30))

    model.add(BatchNormalization(beta_initializer='zeros', gamma_initializer='ones'))

    
     #Hiddlen layer 2
    unit_2 = hp.Int("unit_2", min_value= 4,max_value= 16, step =4)
    activ_fun2 = hp.Choice("activ_fun2", ["tanh","relu"])
    kernal_init2 = hp.Choice("kernal_init2",["he_normal","glorot_uniform"])
    model.add(Dense(units = unit_2, activation = activ_fun2, kernel_initializer=kernal_init2))

    model.add(BatchNormalization(beta_initializer='zeros', gamma_initializer='ones'))

    #Output Layer
    model.add(Dense(units=1, activation="linear"))

    #Optimizer
    opt_choice = hp.Choice("opt_choice",["adam","sgd","rmsprop"])
    learning_rate = hp.Float("learning_rate", min_value = 0.001, max_value=0.1, step = 0.005)

    if opt_choice=="adam":
        optimizer = keras.optimizers.Adam(learning_rate = learning_rate)
    elif opt_choice=="sgd":
        optimizer = keras.optimizers.SGD(learning_rate = learning_rate)
    elif opt_choice=="rmsprop":
        optimizer = keras.optimizers.RMSprop(learning_rate = learning_rate)

    model.compile(optimizer=optimizer, metrics=["r2_score"],loss="mean_squared_error")

    return model

k_tuner = kt.RandomSearch(build_Model, max_trials= 4, objective="val_loss", project_name = "Proj1" )    
k_tuner.search(x_train,y_train, epochs=30, validation_data = (x_test,y_test), batch_size=256,verbose=2)

Trial 4 Complete [00h 00m 27s]
val_loss: 100.8421859741211

Best val_loss So Far: 100.8421859741211
Total elapsed time: 00h 01m 53s

In [71]:
k_tuner.get_best_hyperparameters(1)[0].values

{'unit_1': 24,
 'activ_fun1': 'relu',
 'kernal_init1': 'glorot_uniform',
 'unit_2': 16,
 'activ_fun2': 'relu',
 'kernal_init2': 'he_normal',
 'opt_choice': 'rmsprop',
 'learning_rate': 0.07100000000000001}

In [72]:
model = Sequential()

model.add(Dense(units=24, activation='relu', input_dim=30,kernel_initializer="glorot_uniform"))
model.add(Dense(units=16, activation='relu',kernel_initializer="he_normal"))
model.add(Dense(units=1, activation='linear'))

optimizer = keras.optimizers.RMSprop(learning_rate=0.0710)

model.compile(optimizer=optimizer, metrics=['r2_score'], loss='mean_squared_error')
history = model.fit(x_train, y_train, epochs=50, validation_split=0.2, batch_size=128,verbose=2)

Epoch 1/50

F:\Pallavi\Learnings\Python\Modules\Deep_Learning\tensar\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

100/100 - 3s - 34ms/step - loss: 1090.8394 - r2_score: -2.0127e+00 - val_loss: 477.4969 - val_r2_score: -3.7081e-01
Epoch 2/50
100/100 - 1s - 8ms/step - loss: 334.5982 - r2_score: 0.0759 - val_loss: 232.7578 - val_r2_score: 0.3318
Epoch 3/50
100/100 - 1s - 8ms/step - loss: 237.4731 - r2_score: 0.3441 - val_loss: 199.8722 - val_r2_score: 0.4262
Epoch 4/50
100/100 - 1s - 8ms/step - loss: 183.8411 - r2_score: 0.4923 - val_loss: 353.8673 - val_r2_score: -1.5894e-02
Epoch 5/50
100/100 - 1s - 7ms/step - loss: 170.3559 - r2_score: 0.5295 - val_loss: 136.2585 - val_r2_score: 0.6088
Epoch 6/50
100/100 - 1s - 8ms/step - loss: 162.5369 - r2_score: 0.5511 - val_loss: 112.8478 - val_r2_score: 0.6760
Epoch 7/50
100/100 - 1s - 8ms/step - loss: 162.5656 - r2_score: 0.5510 - val_loss: 120.1450 - val_r2_score: 0.6551
Epoch 8/50
100/100 - 1s - 14ms/step - loss: 159.0122 - r2_score: 0.5608 - val_loss: 136.0095 - val_r2_score: 0.6095
Epoch 9/50
100/100 - 1s - 7ms/step - loss: 157.9244 - r2_score: 0.5638 - val_loss: 156.8755 - val_r2_score: 0.5496
Epoch 10/50
100/100 - 1s - 13ms/step - loss: 152.1630 - r2_score: 0.5797 - val_loss: 119.4540 - val_r2_score: 0.6571
Epoch 11/50
100/100 - 1s - 7ms/step - loss: 151.9452 - r2_score: 0.5803 - val_loss: 150.3582 - val_r2_score: 0.5683
Epoch 12/50
100/100 - 1s - 8ms/step - loss: 154.2210 - r2_score: 0.5741 - val_loss: 117.0089 - val_r2_score: 0.6641
Epoch 13/50
100/100 - 1s - 7ms/step - loss: 150.0578 - r2_score: 0.5856 - val_loss: 172.3898 - val_r2_score: 0.5051
Epoch 14/50
100/100 - 1s - 14ms/step - loss: 151.9438 - r2_score: 0.5804 - val_loss: 124.6845 - val_r2_score: 0.6421
Epoch 15/50
100/100 - 1s - 7ms/step - loss: 146.4458 - r2_score: 0.5955 - val_loss: 131.1060 - val_r2_score: 0.6236
Epoch 16/50
100/100 - 1s - 7ms/step - loss: 150.0887 - r2_score: 0.5855 - val_loss: 163.6937 - val_r2_score: 0.5301
Epoch 17/50
100/100 - 1s - 8ms/step - loss: 146.5530 - r2_score: 0.5952 - val_loss: 137.9310 - val_r2_score: 0.6040
Epoch 18/50
100/100 - 1s - 8ms/step - loss: 149.7143 - r2_score: 0.5865 - val_loss: 164.0228 - val_r2_score: 0.5291
Epoch 19/50
100/100 - 1s - 13ms/step - loss: 147.4057 - r2_score: 0.5929 - val_loss: 114.4139 - val_r2_score: 0.6715
Epoch 20/50
100/100 - 1s - 7ms/step - loss: 146.2321 - r2_score: 0.5961 - val_loss: 219.5675 - val_r2_score: 0.3697
Epoch 21/50
100/100 - 1s - 8ms/step - loss: 148.9019 - r2_score: 0.5888 - val_loss: 135.0473 - val_r2_score: 0.6123
Epoch 22/50
100/100 - 1s - 13ms/step - loss: 147.7561 - r2_score: 0.5919 - val_loss: 130.0321 - val_r2_score: 0.6267
Epoch 23/50
100/100 - 1s - 14ms/step - loss: 155.0147 - r2_score: 0.5719 - val_loss: 95.5434 - val_r2_score: 0.7257
Epoch 24/50
100/100 - 1s - 12ms/step - loss: 145.0640 - r2_score: 0.5994 - val_loss: 97.1859 - val_r2_score: 0.7210
Epoch 25/50
100/100 - 1s - 7ms/step - loss: 147.1335 - r2_score: 0.5936 - val_loss: 151.5473 - val_r2_score: 0.5649
Epoch 26/50
100/100 - 1s - 14ms/step - loss: 143.6634 - r2_score: 0.6032 - val_loss: 166.3913 - val_r2_score: 0.5223
Epoch 27/50
100/100 - 1s - 7ms/step - loss: 143.8934 - r2_score: 0.6026 - val_loss: 94.8410 - val_r2_score: 0.7277
Epoch 28/50
100/100 - 1s - 7ms/step - loss: 141.5641 - r2_score: 0.6090 - val_loss: 106.6335 - val_r2_score: 0.6939
Epoch 29/50
100/100 - 1s - 7ms/step - loss: 153.6843 - r2_score: 0.5755 - val_loss: 129.9458 - val_r2_score: 0.6269
Epoch 30/50
100/100 - 1s - 7ms/step - loss: 141.3212 - r2_score: 0.6097 - val_loss: 112.3213 - val_r2_score: 0.6775
Epoch 31/50
100/100 - 1s - 14ms/step - loss: 146.6548 - r2_score: 0.5950 - val_loss: 95.8451 - val_r2_score: 0.7248
Epoch 32/50
100/100 - 1s - 12ms/step - loss: 153.2119 - r2_score: 0.5769 - val_loss: 173.8127 - val_r2_score: 0.5010
Epoch 33/50
100/100 - 1s - 7ms/step - loss: 135.8283 - r2_score: 0.6249 - val_loss: 172.4319 - val_r2_score: 0.5050
Epoch 34/50
100/100 - 1s - 7ms/step - loss: 140.2016 - r2_score: 0.6128 - val_loss: 97.2595 - val_r2_score: 0.7208
Epoch 35/50
100/100 - 1s - 7ms/step - loss: 140.9788 - r2_score: 0.6106 - val_loss: 218.7403 - val_r2_score: 0.3720
Epoch 36/50
100/100 - 1s - 7ms/step - loss: 158.6664 - r2_score: 0.5618 - val_loss: 252.3870 - val_r2_score: 0.2754
Epoch 37/50
100/100 - 1s - 7ms/step - loss: 137.8088 - r2_score: 0.6194 - val_loss: 97.8521 - val_r2_score: 0.7191
Epoch 38/50
100/100 - 1s - 6ms/step - loss: 135.7548 - r2_score: 0.6251 - val_loss: 137.8007 - val_r2_score: 0.6044
Epoch 39/50
100/100 - 1s - 6ms/step - loss: 133.4490 - r2_score: 0.6314 - val_loss: 123.6249 - val_r2_score: 0.6451
Epoch 40/50
100/100 - 1s - 7ms/step - loss: 133.9173 - r2_score: 0.6301 - val_loss: 173.1594 - val_r2_score: 0.5029
Epoch 41/50
100/100 - 1s - 7ms/step - loss: 134.6209 - r2_score: 0.6282 - val_loss: 132.7780 - val_r2_score: 0.6188
Epoch 42/50
100/100 - 1s - 12ms/step - loss: 133.9457 - r2_score: 0.6301 - val_loss: 105.4870 - val_r2_score: 0.6972
Epoch 43/50
100/100 - 1s - 7ms/step - loss: 129.1357 - r2_score: 0.6433 - val_loss: 95.7418 - val_r2_score: 0.7251
Epoch 44/50
100/100 - 1s - 7ms/step - loss: 133.5250 - r2_score: 0.6312 - val_loss: 185.2899 - val_r2_score: 0.4681
Epoch 45/50
100/100 - 2s - 15ms/step - loss: 132.7469 - r2_score: 0.6334 - val_loss: 117.2439 - val_r2_score: 0.6634
Epoch 46/50
100/100 - 1s - 15ms/step - loss: 128.9119 - r2_score: 0.6440 - val_loss: 96.4541 - val_r2_score: 0.7231
Epoch 47/50
100/100 - 2s - 15ms/step - loss: 132.1711 - r2_score: 0.6350 - val_loss: 98.4874 - val_r2_score: 0.7173
Epoch 48/50
100/100 - 1s - 9ms/step - loss: 127.6490 - r2_score: 0.6475 - val_loss: 150.6093 - val_r2_score: 0.5676
Epoch 49/50
100/100 - 1s - 7ms/step - loss: 130.1109 - r2_score: 0.6407 - val_loss: 125.1346 - val_r2_score: 0.6408
Epoch 50/50
100/100 - 1s - 6ms/step - loss: 128.8976 - r2_score: 0.6440 - val_loss: 117.0106 - val_r2_score: 0.6641

In [73]:
y_train_pred = model.predict(x_train)

mse = mean_squared_error(y_train, y_train_pred)
print("MSE : ",mse)
mae = mean_absolute_error(y_train, y_train_pred)
print("MAE : ", mae)
accuracy = r2_score(y_train, y_train_pred)
print("R2_Score", accuracy)


y_test_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_test_pred)
print("MSE : ",mse)
mae = mean_absolute_error(y_test, y_test_pred)
print("MAE : ", mae)
accuracy = r2_score(y_test, y_test_pred)
print("R2_Score", accuracy)

500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step
MSE :  119.14245181294757
MAE :  8.827004952497482
R2_Score 0.6684306506094938
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
MSE :  125.05836157959439
MAE :  9.051192046852114
R2_Score 0.6427288259327986

In [ ]:
#Traning Accuracy -